{
  description = "Modular NixOS building blocks (hardware + role + home modules) consumed by a per-machine /etc/nixos/flake.nix the bootstrap generates. The repo itself is host-agnostic — no hosts/ directory.";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-26.05";

    home-manager = {
      url = "github:nix-community/home-manager/release-26.05";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    stylix = {
      url = "github:nix-community/stylix/release-26.05";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    nixcord = {
      url = "github:KaylorBen/nixcord";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs = { self, nixpkgs, home-manager, stylix, nixcord, ... }@inputs:
    {
      # mkHost composes a NixOS system from a username + hostname + a list of
      # extra modules. The per-machine /etc/nixos/flake.nix (generated by
      # run.sh) calls this with the modules detected at bootstrap time.
      lib.mkHost = { hostname, username, system ? "x86_64-linux", extraModules ? [] }:
        nixpkgs.lib.nixosSystem {
          inherit system;
          specialArgs = { inherit inputs username hostname; };
          # home-manager and stylix NixOS modules are imported by
          # modules/common/{home-manager,stylix}.nix so each piece owns its
          # own dependencies — importing them here too would duplicate.
          modules = extraModules;
        };

      # All importable modules surfaced as paths so the local flake can pick
      # only what it needs. Bootstrap composes the modules list by category.
      nixosModules = {
        common = {
          base         = ./modules/common/base.nix;
          users        = ./modules/common/users.nix;
          packages     = ./modules/common/packages.nix;
          stylix       = ./modules/common/stylix.nix;
          home-manager = ./modules/common/home-manager.nix;
        };
        hardware = {
          cpu-intel     = ./modules/hardware/cpu-intel.nix;
          cpu-amd       = ./modules/hardware/cpu-amd.nix;
          gpu-intel     = ./modules/hardware/gpu-intel.nix;
          gpu-amd       = ./modules/hardware/gpu-amd.nix;
          gpu-nvidia    = ./modules/hardware/gpu-nvidia.nix;
          vm-hyperv     = ./modules/hardware/vm-hyperv.nix;
          vm-qemu       = ./modules/hardware/vm-qemu.nix;
          vm-vmware     = ./modules/hardware/vm-vmware.nix;
          vm-virtualbox = ./modules/hardware/vm-virtualbox.nix;
        };
        roles = {
          headless      = ./modules/roles/headless.nix;
          desktop       = ./modules/roles/desktop.nix;
          laptop        = ./modules/roles/laptop.nix;
          multi-monitor = ./modules/roles/multi-monitor.nix;
          gaming        = ./modules/roles/gaming.nix;
          gaming-kiosk  = ./modules/roles/gaming-kiosk.nix;
        };
      };
    };
}
