{
  description = "Modular NixOS building blocks (hardware + role + home modules) consumed by a per-machine /etc/nixos/flake.nix the bootstrap generates. The repo itself is host-agnostic — no hosts/ directory.";

  inputs = {
    # Default channel for the x86_64 host. Pinned to nixos-26.05.
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-26.05";

    home-manager = {
      url = "github:nix-community/home-manager/release-26.05";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    stylix = {
      url = "github:nix-community/stylix/release-26.05";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    # Parallel nixos-25.11 trio for the Apple Silicon host. The Asahi
    # installer ISO and the nixos-apple-silicon binary cache are pinned to
    # 25.11; running the Asahi host on 26.05 would skip the cache and force
    # local kernel/Mesa rebuilds (hours of wall-clock on a laptop).
    # Home-manager and Stylix must track the same channel as nixpkgs because
    # their module schemas change between releases.
    nixpkgs-25-11.url = "github:NixOS/nixpkgs/nixos-25.11";

    home-manager-25-11 = {
      url = "github:nix-community/home-manager/release-25.11";
      inputs.nixpkgs.follows = "nixpkgs-25-11";
    };

    stylix-25-11 = {
      url = "github:nix-community/stylix/release-25.11";
      inputs.nixpkgs.follows = "nixpkgs-25-11";
    };

    nixcord = {
      url = "github:KaylorBen/nixcord";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    # Apple Silicon (M1/M2/M3) support: kernel, m1n1/u-boot, peripheral
    # firmware extraction, Asahi Mesa stack. Only pulled in by hosts that
    # import nixosModules.hardware.apple-silicon. Follows nixpkgs-25-11 so
    # the Asahi cache hits — mismatched nixpkgs is the documented
    # foot-gun upstream calls out.
    nixos-apple-silicon = {
      url = "github:nix-community/nixos-apple-silicon";
      inputs.nixpkgs.follows = "nixpkgs-25-11";
    };
  };

  outputs = { self, ... }@inputs:
    let
      # Channel = a matched (nixpkgs, home-manager, stylix) trio. Schemas
      # change between releases, so they must move together.
      channels = {
        "26.05" = {
          nixpkgs      = inputs.nixpkgs;
          home-manager = inputs.home-manager;
          stylix       = inputs.stylix;
        };
        "25.11" = {
          nixpkgs      = inputs.nixpkgs-25-11;
          home-manager = inputs.home-manager-25-11;
          stylix       = inputs.stylix-25-11;
        };
      };
    in
    {
      # mkHost composes a NixOS system from a username + hostname + a list of
      # extra modules. The per-machine /etc/nixos/flake.nix (generated by
      # run.sh) calls this with the modules detected at bootstrap time.
      # `channel` picks which (nixpkgs, home-manager, stylix) trio the host
      # evaluates against; modules reach the active trio via specialArgs.inputs
      # (the .nixpkgs / .home-manager / .stylix attrs are rebound per host).
      lib.mkHost = { hostname, username, system ? "x86_64-linux", channel ? "26.05", extraModules ? [] }:
        let
          ch = channels.${channel};
          hostInputs = inputs // {
            nixpkgs      = ch.nixpkgs;
            home-manager = ch.home-manager;
            stylix       = ch.stylix;
          };
        in
        ch.nixpkgs.lib.nixosSystem {
          inherit system;
          specialArgs = { inputs = hostInputs; inherit username hostname; };
          # home-manager and stylix NixOS modules are imported by
          # modules/common/{home-manager,stylix}.nix so each piece owns its
          # own dependencies — importing them here too would duplicate.
          modules = extraModules;
        };

      # All importable modules surfaced as paths so the local flake can pick
      # only what it needs. Bootstrap composes the modules list by category.
      nixosModules = {
        common = {
          base         = ./modules/common/base.nix;
          users        = ./modules/common/users.nix;
          packages     = ./modules/common/packages.nix;
          stylix       = ./modules/common/stylix.nix;
          home-manager = ./modules/common/home-manager.nix;
        };
        hardware = {
          cpu-intel     = ./modules/hardware/cpu-intel.nix;
          cpu-amd       = ./modules/hardware/cpu-amd.nix;
          gpu-intel     = ./modules/hardware/gpu-intel.nix;
          gpu-amd       = ./modules/hardware/gpu-amd.nix;
          gpu-nvidia    = ./modules/hardware/gpu-nvidia.nix;
          vm-hyperv     = ./modules/hardware/vm-hyperv.nix;
          vm-qemu       = ./modules/hardware/vm-qemu.nix;
          vm-vmware     = ./modules/hardware/vm-vmware.nix;
          vm-virtualbox = ./modules/hardware/vm-virtualbox.nix;
          apple-silicon = ./modules/hardware/apple-silicon.nix;
        };
        roles = {
          headless      = ./modules/roles/headless.nix;
          desktop       = ./modules/roles/desktop.nix;
          laptop        = ./modules/roles/laptop.nix;
          multi-monitor = ./modules/roles/multi-monitor.nix;
          gaming        = ./modules/roles/gaming.nix;
          gaming-kiosk  = ./modules/roles/gaming-kiosk.nix;
          gaming-asahi  = ./modules/roles/gaming-asahi.nix;
        };
      };
    };
}
