#!/usr/bin/env bash
# Bootstrap this NixOS configuration end-to-end.
#
# Usage:
#   git clone <this repo> ~/Projects/nixos
#   cd ~/Projects/nixos
#   ./run.sh
#
# What it does:
#   1. Copies the per-machine hardware-configuration.nix into the repo (once).
#   2. Replaces /etc/nixos with a symlink to the repo so future rebuilds read
#      this tree.
#   3. Adds the channels the imports rely on: <unstable>, <home-manager/nixos>,
#      <stylix>. (Nixcord is fetched inline via builtins.fetchTarball — no
#      channel required.)
#   4. Copies nixos.png into ~/Wallpapers (the path hyprland.nix hands awww).
#   5. Seeds ~/dotfiles/nvim with the LazyVim starter plus the two project
#      overlays (the milkoutside colorscheme and the mason/Nix LSP shim). This
#      is the out-of-store target neovim.nix symlinks ~/.config/nvim to.
#   6. Runs `nixos-rebuild switch`, which builds the system, installs
#      home-manager via the imported NixOS module, and lays down every user
#      config (Hyprland, Waybar, Nixcord/Vencord, Stylix theming, etc.).

set -euo pipefail

REPO_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
TS="$(date +%Y%m%d-%H%M%S)"

# --- 0. Sanity check ---------------------------------------------------------
if ! command -v nixos-rebuild >/dev/null 2>&1; then
  echo "error: nixos-rebuild not found — this script must be run on NixOS." >&2
  exit 1
fi

# --- 1. Bring hardware-configuration.nix into the repo ----------------------
# configuration.nix imports ./hardware-configuration.nix. It is per-machine
# (generated by nixos-generate-config) and stays gitignored.
if [ ! -f "$REPO_DIR/hardware-configuration.nix" ]; then
  if [ -f /etc/nixos/hardware-configuration.nix ]; then
    sudo cp /etc/nixos/hardware-configuration.nix "$REPO_DIR/hardware-configuration.nix"
    sudo chown "$USER:$(id -gn)" "$REPO_DIR/hardware-configuration.nix"
  else
    echo "error: /etc/nixos/hardware-configuration.nix not found." >&2
    echo "       run 'sudo nixos-generate-config' first." >&2
    exit 1
  fi
fi

# --- 2. Point /etc/nixos at this repo ---------------------------------------
# nixos-rebuild reads /etc/nixos/configuration.nix; making /etc/nixos itself a
# symlink to the repo keeps relative imports (./home.nix, ./stylix.nix, ...)
# resolving correctly regardless of how Nix handles path arithmetic through
# symlinks.
if [ ! -L /etc/nixos ] || [ "$(readlink -f /etc/nixos)" != "$REPO_DIR" ]; then
  if [ -e /etc/nixos ] && [ ! -L /etc/nixos ]; then
    sudo mv /etc/nixos "/etc/nixos.bak.$TS"
    echo "==> Backed up previous /etc/nixos to /etc/nixos.bak.$TS"
  elif [ -L /etc/nixos ]; then
    sudo rm /etc/nixos
  fi
  sudo ln -s "$REPO_DIR" /etc/nixos
  echo "==> /etc/nixos -> $REPO_DIR"
fi

# --- 3. Channels referenced by the configuration ----------------------------
#   configuration.nix : <home-manager/nixos>, <unstable>
#   stylix.nix        : <stylix>
#   nixcord.nix       : fetchTarball, no channel needed
echo "==> Adding/updating Nix channels (unstable, home-manager, stylix)..."
sudo nix-channel --add https://nixos.org/channels/nixos-unstable unstable
sudo nix-channel --add https://github.com/nix-community/home-manager/archive/release-26.05.tar.gz home-manager
sudo nix-channel --add https://github.com/nix-community/stylix/archive/release-26.05.tar.gz stylix
sudo nix-channel --update

# --- 4. Wallpaper (referenced by hyprland.nix's awww autostart) -------------
# hyprland.nix points awww at ~/Wallpapers/nixos.png; copy it out of the repo.
if [ -f "$REPO_DIR/nixos.png" ]; then
  mkdir -p "$HOME/Wallpapers"
  cp -u "$REPO_DIR/nixos.png" "$HOME/Wallpapers/nixos.png"
fi

# --- 5. LazyVim dotfiles (out-of-store target from neovim.nix) --------------
if [ ! -d "$HOME/dotfiles/nvim" ]; then
  echo "==> Cloning LazyVim starter into ~/dotfiles/nvim ..."
  git clone https://github.com/LazyVim/starter "$HOME/dotfiles/nvim"
  rm -rf "$HOME/dotfiles/nvim/.git"
  mkdir -p "$HOME/dotfiles/nvim/lua/plugins"

  cat > "$HOME/dotfiles/nvim/lua/plugins/colorscheme.lua" << 'LUA'
return {
  { "color-schemes/milkoutside.nvim", lazy = false, priority = 1000, opts = {} },
  { "LazyVim/LazyVim", opts = { colorscheme = "milkoutside" } },
}
LUA

  cat > "$HOME/dotfiles/nvim/lua/plugins/nixos.lua" << 'LUA'
return {
  {
    "neovim/nvim-lspconfig",
    opts = function(_, opts)
      opts.servers = opts.servers or {}
      for _, s in pairs(opts.servers) do
        if type(s) == "table" then s.mason = false end
      end
    end,
  },
  { "mason-org/mason.nvim", enabled = false },
  { "mason-org/mason-lspconfig.nvim", enabled = false },
}
LUA
fi

# --- 6. Build & activate -----------------------------------------------------
# This pulls home-manager (via <home-manager/nixos> in configuration.nix), which
# in turn imports the nixcord home module and writes the Vencord config, the
# Hyprland Lua config, the Waybar config, the Starship prompt, the Stylix
# palette, etc. — every user-level piece of the rice lands in a single switch.
echo "==> Building the system. First run downloads everything; expect a wait."
sudo nixos-rebuild switch

echo
echo "Bootstrap complete."
echo "Log out (or reboot) to drop into the Hyprland session defined by greetd."
